// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_an_ragdoll2[] =
"<?xml version=\"1.0\"?>"
"<!-- ragdoll2.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.animesh.animnode.ragdoll2</name>"
"        <implementation>Ragdoll2NodeManager</implementation>"
"        <description>Crystal Space ragdoll animation node of an animated Mesh</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef Ragdoll2NodeManager_FACTORY_REGISTER_DEFINED 
  #define Ragdoll2NodeManager_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(Ragdoll2NodeManager) 
  #endif

class an_ragdoll2
{
SCF_REGISTER_STATIC_LIBRARY(an_ragdoll2,metainfo_an_ragdoll2)
  #ifndef Ragdoll2NodeManager_FACTORY_REGISTERED 
  #define Ragdoll2NodeManager_FACTORY_REGISTERED 
    Ragdoll2NodeManager_StaticInit Ragdoll2NodeManager_static_init__; 
  #endif
public:
 an_ragdoll2();
};
an_ragdoll2::an_ragdoll2() {}

}
