// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_assimpldr[] =
"<?xml version=\"1.0\"?>"
"<!-- assimpldr.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.loader.factory.assimp</name>"
"        <implementation>AssimpLoader</implementation>"
"        <description>Open Asset Import Library loader for Crystal Space</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef AssimpLoader_FACTORY_REGISTER_DEFINED 
  #define AssimpLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(AssimpLoader) 
  #endif

class assimpldr
{
SCF_REGISTER_STATIC_LIBRARY(assimpldr,metainfo_assimpldr)
  #ifndef AssimpLoader_FACTORY_REGISTERED 
  #define AssimpLoader_FACTORY_REGISTERED 
    AssimpLoader_StaticInit AssimpLoader_static_init__; 
  #endif
public:
 assimpldr();
};
assimpldr::assimpldr() {}

}
