// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_cssocket[] =
"<?xml version=\"1.0\"?>"
"<!-- cssocket.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.network.socket.manager</name>"
"        <implementation>SocketManager</implementation>"
"        <description>CrystalSpace Socket Plugin</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef SocketManager_FACTORY_REGISTER_DEFINED 
  #define SocketManager_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(SocketManager) 
  #endif

class cssocket
{
SCF_REGISTER_STATIC_LIBRARY(cssocket,metainfo_cssocket)
  #ifndef SocketManager_FACTORY_REGISTERED 
  #define SocketManager_FACTORY_REGISTERED 
    SocketManager_StaticInit SocketManager_static_init__; 
  #endif
public:
 cssocket();
};
cssocket::cssocket() {}

}
