// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_csnetworkeventmanager[] =
"<?xml version=\"1.0\"?>"
"<!-- csnetworkeventmanager.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.network.event.manager</name>"
"        <implementation>EventManager</implementation>"
"        <description>CrystalSpace Event Manager Plugin</description>"
"        <requires>"
"          <class>crystalspace.network.socket.manager</class>"
"        </requires>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef EventManager_FACTORY_REGISTER_DEFINED 
  #define EventManager_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(EventManager) 
  #endif

class csnetworkeventmanager
{
SCF_REGISTER_STATIC_LIBRARY(csnetworkeventmanager,metainfo_csnetworkeventmanager)
  #ifndef EventManager_FACTORY_REGISTERED 
  #define EventManager_FACTORY_REGISTERED 
    EventManager_StaticInit EventManager_static_init__; 
  #endif
public:
 csnetworkeventmanager();
};
csnetworkeventmanager::csnetworkeventmanager() {}

}
