// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_convexdecompose[] =
"<?xml version=\"1.0\"?>"
"<!-- hacd.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.convexdecompose.hacd</name>"
"        <implementation>ConvexDecomposer</implementation>"
"        <description>Decompose concave meshes in a convex set</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef ConvexDecomposer_FACTORY_REGISTER_DEFINED 
  #define ConvexDecomposer_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(ConvexDecomposer) 
  #endif

class convexdecompose
{
SCF_REGISTER_STATIC_LIBRARY(convexdecompose,metainfo_convexdecompose)
  #ifndef ConvexDecomposer_FACTORY_REGISTERED 
  #define ConvexDecomposer_FACTORY_REGISTERED 
    ConvexDecomposer_StaticInit ConvexDecomposer_static_init__; 
  #endif
public:
 convexdecompose();
};
convexdecompose::convexdecompose() {}

}
