// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_modelldr[] =
"<?xml version=\"1.0\"?>"
"<!-- modelldr.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.loader.skeleton.model</name>"
"        <implementation>ModelLoader</implementation>"
"        <description>Crystal Space loader of the physical description of the skeleton an animated mesh</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef ModelLoader_FACTORY_REGISTER_DEFINED 
  #define ModelLoader_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(ModelLoader) 
  #endif

class modelldr
{
SCF_REGISTER_STATIC_LIBRARY(modelldr,metainfo_modelldr)
  #ifndef ModelLoader_FACTORY_REGISTERED 
  #define ModelLoader_FACTORY_REGISTERED 
    ModelLoader_StaticInit ModelLoader_static_init__; 
  #endif
public:
 modelldr();
};
modelldr::modelldr() {}

}
