// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_posteffect[] =
"<?xml version=\"1.0\"?>"
"<!-- posteffect.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.rendermanager.posteffect</name>"
"        <implementation>PostEffectManager</implementation>"
"        <description>Post Effects implementation</description>"
"        <requires>"
"          <class>crystalspace.engine.</class>"
"          <class>crystalspace.graphics3d.</class>         "
"        </requires>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef PostEffectManager_FACTORY_REGISTER_DEFINED 
  #define PostEffectManager_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(PostEffectManager) 
  #endif

class posteffect
{
SCF_REGISTER_STATIC_LIBRARY(posteffect,metainfo_posteffect)
  #ifndef PostEffectManager_FACTORY_REGISTERED 
  #define PostEffectManager_FACTORY_REGISTERED 
    PostEffectManager_StaticInit PostEffectManager_static_init__; 
  #endif
public:
 posteffect();
};
posteffect::posteffect() {}

}
