// This file is automatically generated.
#include "cssysdef.h"
#include "csutil/scf.h"

// Put static linking stuff into own section.
// The idea is that this allows the section to be swapped out but not
// swapped in again b/c something else in it was needed.
#if !defined(CS_DEBUG) && defined(CS_COMPILER_MSVC)
#pragma const_seg(".CSmetai")
#pragma comment(linker, "/section:.CSmetai,r")
#pragma code_seg(".CSmeta")
#pragma comment(linker, "/section:.CSmeta,er")
#pragma comment(linker, "/merge:.CSmetai=.CSmeta")
#endif

namespace csStaticPluginInit
{
static char const metainfo_skeletonmodel[] =
"<?xml version=\"1.0\"?>"
"<!-- skeletonmodel.csplugin -->"
"<plugin>"
"  <scf>"
"    <classes>"
"      <class>"
"        <name>crystalspace.mesh.animesh.model</name>"
"        <implementation>ModelManager</implementation>"
"        <description>Physical description of the skeleton of an animated mesh</description>"
"      </class>"
"    </classes>"
"  </scf>"
"</plugin>"
;
  #ifndef ModelManager_FACTORY_REGISTER_DEFINED 
  #define ModelManager_FACTORY_REGISTER_DEFINED 
    SCF_DEFINE_FACTORY_FUNC_REGISTRATION(ModelManager) 
  #endif

class skeletonmodel
{
SCF_REGISTER_STATIC_LIBRARY(skeletonmodel,metainfo_skeletonmodel)
  #ifndef ModelManager_FACTORY_REGISTERED 
  #define ModelManager_FACTORY_REGISTERED 
    ModelManager_StaticInit ModelManager_static_init__; 
  #endif
public:
 skeletonmodel();
};
skeletonmodel::skeletonmodel() {}

}
